version: "3"
services:
  pack:
    build: ./pack
    volumes:
      - web-dir:/usr/local/webapps
  webapp:
    build: ./prod
    depends_on:
      - pack
    ports:
      - "8080:8080"
    volumes:
      - web-dir:/usr/local/pack
    
volumes:
  web-dir: